objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>Home Country list</description>
        <label>Legal Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <description>Cost</description>
        <label>Cost</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fee</description>
        <label>Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cost per Calendar Month</fullName>
                </value>
                <value>
                    <fullName>ATM Fee in other currencies</fullName>
                </value>
                <value>
                    <fullName>Card Replacement Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/N26CustomerProductInfoApexController.cls
public class N26CustomerProductInfoApexController {
    @AuraEnabled
    public static ProductInformationWrapper getCaseContactInfo(String caseId){
        String contactId = [SELECT ContactId FROM Case WHERE Id =: caseId].ContactId;
        Contact caseContact = [SELECT Id, Name, Product__c, Home_Country__c FROM Contact WHERE Id =: contactId ];
        
        List<Product__c> productList = [SELECT id, Country__c, Package__c, Type__c, Cost__c, Fee__c
                          	FROM Product__c
                          	WHERE Country__c = : caseContact.Home_Country__c 
                            AND Type__c = : caseContact.Product__c];
        
        List<PackageInfoWrapper> packageInfoList = new List<PackageInfoWrapper>();
        for(Product__c productInfo : productList){
            String price;
            if(productInfo.Fee__c == false){
                price = '€ ' + productInfo.Cost__c;
            }else {
                if(productInfo.Cost__c != 0){
                    price = 'Free';
                }
                else{
                    price = productInfo.Cost__c + '%';
                }
            }
            PackageInfoWrapper packageInfo = new PackageInfoWrapper(productInfo.Package__c, price);
            packageInfoList.add(packageInfo);
        }
        
        ProductInformationWrapper productInfoWrapper = new ProductInformationWrapper(caseContact, packageInfoList);
        return productInfoWrapper;
    }


    public class ProductInformationWrapper{
        @AuraEnabled
        public Contact contactInfo {get;set;}
        @AuraEnabled
        public List<PackageInfoWrapper> packageInfoList{get;set;}
            
        public ProductInformationWrapper (Contact contactInfo, List<PackageInfoWrapper> packageInfoList){
            this.contactInfo = contactInfo;
            this.packageInfoList = packageInfoList;
        }
    }
    
    public class PackageInfoWrapper {
        @AuraEnabled
        public String packageName  {get;set;}
        @AuraEnabled
        public String packagePrice {get;set;}
            
        public PackageInfoWrapper (String packageName, String packagePrice){
            this.packageName = packageName;   
            this.packagePrice = packagePrice; 
        }
    }
}