objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>Home Country list</description>
        <label>Legal Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>language__c</fullName>
        <description>Language Iso 639-1 Code</description>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                    <default>true</default>
                    <label>en</label>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <description>Cost</description>
        <label>Cost</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cost per Calendar Month</fullName>
                </value>
                <value>
                    <fullName>ATM Fee in other currencies</fullName>
                </value>
                <value>
                    <fullName>Card Replacement Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/N26CustomerProductInfoApexControllerTest.cls
@isTest
public class N26CustomerProductInfoApexControllerTest {
	@testSetup
    public static void createData(){
        Contact testContact = new Contact();
        testContact.FirstName = 'Maria';
        testContact.LastName = 'da Gloria de jesus';
        testContact.Product__c = 'Standard';
        testContact.Home_Country__c = 'DE';
        testContact.language__c = 'en';
        insert testContact; 
        
        Product__c costPerCalendar = new Product__c();
        costPerCalendar.Country__c = 'DE';
        costPerCalendar.Package__c = 'Cost per Calendar Month';
        costPerCalendar.Type__c = 'Standard';
        costPerCalendar.Cost__c = 0;
        insert costPerCalendar;
        
        Product__c cardReplacement = new Product__c();
        cardReplacement.Country__c = 'DE';
        cardReplacement.Package__c = 'Card Replacement Cost';
        cardReplacement.Type__c = 'Standard';
        cardReplacement.Cost__c = 6;
        insert cardReplacement;
        
        Case caseTest = new Case();
        caseTest.Origin = 'Web';
        caseTest.ContactId = testContact.Id;
        caseTest.Subject = 'Test Case';
        insert caseTest;
    }
    
    @isTest
    public static void getCaseContactInfoTest(){
        String caseId = [SELECT Id FROM Case LIMIT 1].Id;
        N26CustomerProductInfoApexController.ProductInformationWrapper allInfo = N26CustomerProductInfoApexController.getCaseContactInfo(caseId);
        system.assertEquals('Maria da Gloria de jesus', allInfo.contactInfo.Name);
        system.assertEquals('DE', allInfo.contactInfo.Home_Country__c);
        system.assertEquals('Standard', allInfo.contactInfo.Product__c);
    }
}